services :
  test-db:
    image: mariadb
    restart: always
    environment:
      - TZ="Asia/Seoul"
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=test123
      - MARIADB_USER=test
      - MARIADB_DATABASE=testDB
      - MARIADB_PASSWORD=test123
    volumes:
      - ./test_maria_data:/etc/mysql/conf.d
    ports:
      - 3307:3306
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

