# 로컬 / 도커와 환경 분리하기  DB
spring:
  profiles:
    default: local

  datasource:
    url: jdbc:mariadb://localhost:3306/mydb  # ✅ maria **db**!
    username: root
    password: pwd123
    driver-class-name: org.mariadb.jdbc.Driver  # ✅ maria **driver**

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret-key: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  access-token-expired-time: 1800000             # 개발 환경에서는 30분으로 설정
  refresh-token-expired-time: 86400000

---


