
spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/testDB
    username: root
    password: test123
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true